### PR TITLE
feat: add graphql lsp

### PR DESCRIPTION
**Pull request by affanshahid**
Solves https://github.com/11bit/zed-extension-graphql/issues/7

Autocomplete currently working inside `.graphql` files. Though it currently shows duplicate suggestions.
image

Also working inside an embedded context:
image

The duplicate suggestions only seem to happen in GraphQL files.

Question: Should the LSP be registered as "graphql-language-server" or just "graphql"? The official Zed extensions have examples of both, though most use the latter pattern.

### CODE REVIEW

**Comment by 11bit** [comment]
Very good start 🔥 Hopefully we can solve duplicates

**Comment by onx2** [comment]
Wow that was quick, thanks!! Do you mind adding a note about how to use as well? Or does it use the same file that I mentioned in the issue?

**Comment by affanshahid** [comment]
I've updated the README with usage information. It works similarly to the VSCode extension that you may already be using so it might work out of the box for you.

**Comment by affanshahid** [comment]
I've fixed the duplicate suggestions issue:
image

It was due to duplicate registration of the LSP for `.graphql` files since GraphQL was listed in both the `language` and `languages` key in `extension.toml`. Though it's weird Zed even allows registering the same LSP twice for the same file.

**Review by 11bit — APPROVED** [review]
Awesome 🔥

**Comment by affanshahid** [comment]
@11bit Can you also tag the release and open a PR on the Zed extensions repo to use the new release so this is available on the Zed marketplace?

**Comment by 11bit** [comment]
Sure

**Comment by 11bit** [comment]
Update is available on marketplace. Thanks @affanshahid!

**Comment by onx2** [comment]
Works like a charm, thank you!!
image

**Pull request merged**
